###
GET http://localhost:8000/search/statistics/titulado HTTP/1.1
###
GET http://localhost:8000/search/statistics/egresado HTTP/1.1
###
GET http://localhost:8000/search/statistics/bachiller HTTP/1.1




###
GET http://localhost:8000/search/qgraduationyear/2017 HTTP/1.1
###
GET http://localhost:8000/search/qtypeuser/titulado HTTP/1.1
###
GET http://localhost:8000/search/qspecialty/Frontend HTTP/1.1
###
GET http://localhost:8000/search/qlocation/%Puno% HTTP/1.1